public with sharing class AutomatePointsBuilderContext {
  public String productCode { get; set; }
  public String tier { get; set; }
  public Integer release { get; set; }
  public Boolean isGte11 { get; set; }
  public Integer TActions { get; set; }
  public Integer MActions { get; set; }
  public Integer NActions { get; set; }
  public Integer PActions { get; set; }
  public Integer bots { get; set; }
  public Integer studios { get; set; }
  public Integer webSmcs { get; set; }
}